version: '3.1'
services:
    mysql:
        container_name: lastctf_mysql
        image: 'mysql:5.7'
        working_dir: /application
        environment:
            - 'MYSQL_ROOT_PASSWORD=x5cu#5zr7Mkaf'
            - MYSQL_DATABASE=lastctf
            - MYSQL_USER=userctf
            - MYSQL_PASSWORD=userctf
        ports:
            - '3309:3306'
        volumes:
            - './src:/application'
            - ./phpdocker/docker-sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './src:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '10002:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './src:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
